# Generated by Django 4.2 on 2025-11-25 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0029_issuestatus_threshold_days_alter_issuestatus_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this integration", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        default=dict, help_text="Encrypted API keys, tokens, etc."
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Provider-specific settings (sender ID, from email)",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Use as default for this provider type"
                    ),
                ),
                (
                    "is_test_mode",
                    models.BooleanField(
                        default=True, help_text="Run in sandbox/test mode"
                    ),
                ),
                ("total_sent", models.IntegerField(default=0)),
                ("total_delivered", models.IntegerField(default=0)),
                ("total_failed", models.IntegerField(default=0)),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_test_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("pending", "Pending"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_test_message", models.TextField(blank=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        db_index=True,
                        help_text="Phone number or email address",
                        max_length=255,
                    ),
                ),
                ("recipient_name", models.CharField(blank=True, max_length=200)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Provider's message ID for tracking",
                        max_length=255,
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full provider response"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Cost in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Provider identifier (africas_talking, twilio, sendgrid, etc.)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")], max_length=10
                    ),
                ),
                (
                    "supports_templates",
                    models.BooleanField(
                        default=False,
                        help_text="Whether provider has native template support",
                    ),
                ),
                (
                    "supports_tracking",
                    models.BooleanField(
                        default=False,
                        help_text="Whether provider supports open/click tracking",
                    ),
                ),
                (
                    "max_recipients_per_request",
                    models.IntegerField(
                        default=1, help_text="Maximum recipients per request"
                    ),
                ),
                (
                    "rate_limit_per_second",
                    models.IntegerField(
                        blank=True, help_text="Maximum requests per second", null=True
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.IntegerField(
                        blank=True, help_text="Maximum requests per minute", null=True
                    ),
                ),
                (
                    "rate_limit_per_hour",
                    models.IntegerField(
                        blank=True, help_text="Maximum requests per hour", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Provider",
                "verbose_name_plural": "Notification Providers",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Rule name", max_length=200)),
                (
                    "trigger_event",
                    models.CharField(
                        db_index=True,
                        help_text="Event that triggers this rule",
                        max_length=100,
                    ),
                ),
                (
                    "trigger_conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Additional conditions (category, region, etc.)",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("citizen", "Citizen"),
                            ("assigned_worker", "Assigned Worker"),
                            ("facilitator", "Facilitator"),
                            ("regional_managers", "Regional Managers"),
                            ("custom", "Custom Recipients"),
                        ],
                        help_text="Who receives the notification",
                        max_length=50,
                    ),
                ),
                (
                    "custom_recipients",
                    models.JSONField(
                        blank=True, default=list, help_text="List of custom recipients"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=10, help_text="Execution priority (higher first)"
                    ),
                ),
                (
                    "max_per_hour",
                    models.IntegerField(
                        blank=True, help_text="Rate limit per hour", null=True
                    ),
                ),
                (
                    "max_per_day",
                    models.IntegerField(
                        blank=True, help_text="Rate limit per day", null=True
                    ),
                ),
                ("times_triggered", models.IntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Rule",
                "verbose_name_plural": "Notification Rules",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")], max_length=10
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        db_index=True,
                        help_text="Event that triggers this template",
                        max_length=100,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject (not used for SMS)",
                        max_length=500,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Template body with {{variable}} placeholders"
                    ),
                ),
                (
                    "available_variables",
                    models.JSONField(
                        default=list, help_text="List of available variables"
                    ),
                ),
                (
                    "is_system_template",
                    models.BooleanField(
                        default=False, help_text="System templates cannot be deleted"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Webhook URL", max_length=500, unique=True
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Webhook signing secret", max_length=255
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list, help_text="List of events this webhook handles"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "verify_signature",
                    models.BooleanField(
                        default=True, help_text="Whether to verify webhook signature"
                    ),
                ),
                ("total_received", models.IntegerField(default=0)),
                ("total_processed", models.IntegerField(default=0)),
                ("total_failed", models.IntegerField(default=0)),
                ("last_received_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["trigger_event", "is_active"],
                name="integration_trigger_4071c4_idx",
            ),
        ),
        migrations.AddField(
            model_name="notificationrule",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rules",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="notificationrule",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rules",
                to="integrations.notificationtemplate",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logs",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_logs",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="integrations.notificationtemplate",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="integrations",
                to="integrations.notificationprovider",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrule",
            index=models.Index(
                fields=["trigger_event", "is_active"],
                name="integration_trigger_21f07c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrule",
            index=models.Index(
                fields=["priority"], name="integration_priorit_0455a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["status", "created_at"], name="integration_status_8a9480_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["recipient"], name="integration_recipie_79f010_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["integration", "status"], name="integration_integra_c751cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(fields=["issue"], name="integration_issue_i_b95877_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["provider_message_id"], name="integration_provide_fdf6d7_idx"
            ),
        ),
    ]
