# Generated by Django 4.2 on 2025-08-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ETLExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etl_name", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("records_processed", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("SCHEDULER", "Scheduled Task"),
                            ("MANUAL", "Manual Execution"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
