# Generated by Django 4.2 on 2025-08-29 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import attachments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0012_remove_issue_issue_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="couchDB document _id",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="File attached to the issue",
                        upload_to=attachments.models.issue_attachment_upload_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created date"),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="issues.issue",
                        verbose_name="Issue",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["-created_date"],
            },
        ),
        migrations.AddIndex(
            model_name="issueattachment",
            index=models.Index(fields=["issue", "created_date"], name="attachments_issue_i_dad28a_idx"),
        ),
        migrations.AddIndex(
            model_name="issueattachment",
            index=models.Index(fields=["uploaded_by"], name="attachments_uploade_9456aa_idx"),
        ),
    ]
