# Generated by Django 4.2 on 2025-09-04 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueattachment",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="issueattachment",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at"),
        ),
    ]
