# Generated by Django 5.2.5 on 2025-09-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0002_issueattachment_updated_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IssueAttachment",
        ),
    ]
