branch-defaults:
  default:
    environment: grm-env
environment-defaults:
  grm-env:
    branch: null
    repository: null
global:
  application_name: grm
  default_ec2_keyname: togo-env
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
