# Generated by Django 4.2 on 2025-08-05 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdministrativeRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "administrative_level",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="issues.administrativeregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Region",
                "verbose_name_plural": "Administrative Regions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IssueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Issue Category",
                "verbose_name_plural": "Issue Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IssueStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("final_status", models.BooleanField(default=False)),
                ("initial_status", models.BooleanField(default=False)),
                ("rejected_status", models.BooleanField(default=False)),
                ("open_status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Issue Status",
                "verbose_name_plural": "Issue Status",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IssueType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Issue Type",
                "verbose_name_plural": "Issue Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intake_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "administrative_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="issues.administrativeregion",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="issues.issuecategory",
                    ),
                ),
                (
                    "issue_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="issues.issuetype",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="issues.issuestatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
                "ordering": ["-intake_date"],
            },
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["intake_date", "administrative_region"],
                name="issues_issu_intake__93f28b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["administrative_region", "status"],
                name="issues_issu_adminis_a1a2d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["administrative_region", "category"],
                name="issues_issu_adminis_8480a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["administrative_region", "issue_type"],
                name="issues_issu_adminis_b4efa7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="administrativeregion",
            index=models.Index(
                fields=["parent", "administrative_level"],
                name="issues_admi_parent__d68565_idx",
            ),
        ),
    ]
