# Generated by Django 4.2 on 2025-08-12 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_assigned_department(apps, schema_editor):
    IssueDepartment = apps.get_model("issues", "IssueDepartment")
    AdministrativeLevel = apps.get_model("issues", "AdministrativeLevel")
    IssueDepartmentAdministrativeLevel = apps.get_model("issues", "IssueDepartmentAdministrativeLevel")

    IssueDepartment.objects.get_or_create(id=1)
    AdministrativeLevel.objects.get_or_create(id=1, name="country")
    IssueDepartmentAdministrativeLevel.objects.create(
        id=1,
        department_id=1,
        administrative_level_id=1,
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Administrative Level",
                "verbose_name_plural": "Administrative Levels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IssueDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "head",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Department",
                "verbose_name_plural": "Issue Departments",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="issuecategory",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="issuecategory",
            name="confidentiality_level",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="issuecategory",
            name="redirection_protocol",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="IssueDepartmentAdministrativeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "administrative_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issues.administrativelevel",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issues.issuedepartment",
                    ),
                ),
            ],
            options={
                "unique_together": {("department", "administrative_level")},
            },
        ),
        migrations.AddField(
            model_name="administrativeregion",
            name="administrative_level_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="issues.administrativelevel",
            ),
        ),
        migrations.RunPython(create_default_assigned_department),
        migrations.AddField(
            model_name="issuecategory",
            name="assigned_appeal_department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_appeal_categories",
                to="issues.issuedepartmentadministrativelevel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issuecategory",
            name="assigned_department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_categories",
                to="issues.issuedepartmentadministrativelevel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issuecategory",
            name="assigned_escalation_department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_escalation_categories",
                to="issues.issuedepartmentadministrativelevel",
            ),
            preserve_default=False,
        ),
    ]
