# Generated by Django 4.2 on 2025-08-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_administrativelevel_issuedepartment_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="administrativeregion",
            name="issues_admi_parent__d68565_idx",
        ),
        migrations.RemoveField(
            model_name="administrativeregion",
            name="administrative_level",
        ),
        migrations.AddIndex(
            model_name="administrativeregion",
            index=models.Index(
                fields=["parent", "administrative_level_fk"],
                name="issues_admi_parent__6cceab_idx",
            ),
        ),
    ]
