# Generated by Django 4.2 on 2025-08-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "issues",
            "0003_remove_administrativeregion_issues_admi_parent__d68565_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="administrativeregion",
            name="issues_admi_parent__6cceab_idx",
        ),
        migrations.RenameField(
            model_name="administrativeregion",
            old_name="administrative_level_fk",
            new_name="administrative_level",
        ),
        migrations.AddIndex(
            model_name="administrativeregion",
            index=models.Index(
                fields=["parent", "administrative_level"],
                name="issues_admi_parent__442441_idx",
            ),
        ),
    ]
