# Generated by Django 4.2 on 2025-08-12 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "issues",
            "0004_remove_administrativeregion_issues_admi_parent__6cceab_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativeregion",
            name="administrative_level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="issues.administrativelevel",
            ),
            preserve_default=False,
        ),
    ]
