# Generated by Django 4.2 on 2025-08-13 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0006_alter_issuedepartment_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="assignee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignee_issues",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issue",
            name="reporter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reporter_issues",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issue",
            name="title",
            field=models.CharField(default="default", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issue",
            name="tracking_code",
            field=models.CharField(default="default", max_length=255),
            preserve_default=False,
        ),
    ]
