# Generated by Django 4.2 on 2025-08-15 22:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0007_issue_assignee_issue_reporter_issue_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenAgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CitizenGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("citizen_group", "citizen_group"),
                            ("citizen_group_2", "citizen_group_2"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SubComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="issue",
            name="contact_information",
            field=models.CharField(
                blank=True,
                help_text="The contact phone, email, whatsapp or other method data",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="contact_medium",
            field=models.CharField(
                blank=True,
                choices=[
                    ("channel-alert", "channel-alert"),
                    ("facilitator", "facilitator"),
                    ("anonymous", "anonymous"),
                ],
                default="channel-alert",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="contact_method",
            field=models.CharField(
                choices=[
                    ("email", "email"),
                    ("phone_number", "phone_number"),
                    ("whatsapp", "whatsapp"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When was the issue created in DB",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="issue_date",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When was the issue happened",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="issue_location",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific administrative location where the issue occurred.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="located_issues",
                to="issues.administrativeregion",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="location_description",
            field=models.TextField(blank=True, help_text="A textual description of the issue's location."),
        ),
        migrations.AddField(
            model_name="issue",
            name="ongoing_issue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="resolution_date",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When was the issue was resolved",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="intake_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="When was the issue was reported",
            ),
        ),
        migrations.CreateModel(
            name="IssueSubType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="issues.issuesubtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Subtype",
                "verbose_name_plural": "Issue Subtypes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "organization_behalf_someone",
                                "organization_behalf_someone",
                            ),
                            ("on_behalf_of_someone", "on_behalf_of_someone"),
                            ("keep_name_confidential", "keep_name_confidential"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "age_group",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_group_citizen",
                        to="issues.citizenagegroup",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_citizen",
                        to="issues.citizengroup",
                    ),
                ),
                (
                    "group_2",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group2_citizen",
                        to="issues.citizengroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="issue",
            name="citizen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citizen_issues",
                to="issues.citizen",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="component",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="issues.component",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="issue_sub_type",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="issues.issuesubtype",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="sub_component",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="issues.subcomponent",
            ),
        ),
    ]
