# Generated by Django 4.2 on 2025-08-13 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0007_issue_assignee_issue_reporter_issue_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="IssueSubType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Issue Subtype",
                "verbose_name_plural": "Issue Subtypes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="citizen",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="issue",
            name="citizen_age_group",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="issue",
            name="citizen_group",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="issue",
            name="citizen_group_2",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="issue",
            name="citizen_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="issue",
            name="contact_info",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="issue",
            name="contact_medium",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="issue",
            name="contact_method",
            field=models.CharField(
                choices=[
                    ("email", "email"),
                    ("phone_number", "phone_number"),
                    ("whatsapp", "whatsapp"),
                ],
                default="email",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="issue_location",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific administrative location where the issue occurred.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="located_issues",
                to="issues.administrativeregion",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="location_description",
            field=models.TextField(
                blank=True, help_text="A textual description of the issue's location."
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="ongoing_issue",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="issue",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="issues.component",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="issue_sub_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="issues.issuesubtype",
            ),
        ),
    ]
