# Generated by Django 4.2 on 2025-08-19 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0008_citizenagegroup_citizengroup_component_subcomponent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="escalate_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="escalated_date",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="internal_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="age_group_citizen",
                to="issues.citizenagegroup",
            ),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_citizen",
                to="issues.citizengroup",
            ),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="group_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group2_citizen",
                to="issues.citizengroup",
            ),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("organization_behalf_someone", "organization_behalf_someone"),
                    ("on_behalf_of_someone", "on_behalf_of_someone"),
                    ("keep_name_confidential", "keep_name_confidential"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="administrative_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="issues.administrativeregion",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="issues.issuecategory",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="contact_information",
            field=models.CharField(
                blank=True,
                help_text="The contact phone, email, whatsapp or other method data",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "email"),
                    ("phone_number", "phone_number"),
                    ("whatsapp", "whatsapp"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="intake_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=django.utils.timezone.now,
                help_text="When was the issue was reported",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="issue_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="issues.issuetype",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="location_description",
            field=models.TextField(
                blank=True,
                help_text="A textual description of the issue's location.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="issues.issuestatus",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
