# Generated by Django 5.2.5 on 2025-08-15 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_component_issuesubtype_subcomponent_issue_citizen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='issuesubtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='issues.issuesubtype'),
        ),
    ]
