# Generated by Django 5.2.5 on 2025-08-15 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_component_issuesubtype_subcomponent_issue_citizen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('organization_behalf_someone', 'organization_behalf_someone'), ('on_behalf_of_someone', 'on_behalf_of_someone'), ('keep_name_confidential', 'keep_name_confidential')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenAgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(blank=True, choices=[('citizen_group', 'citizen_group'), ('citizen_group_2', 'citizen_group_2')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='citizen_age_group',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='citizen_group',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='citizen_group_2',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='citizen_type',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolution_at',
        ),
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='issue',
            name='contact_information',
            field=models.CharField(blank=True, help_text='The contact phone, email, whatsapp or other method data', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='When was the issue created in DB', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='When was the issue happened', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='When was the issue was resolved', null=True),
        ),
        migrations.AddField(
            model_name='issuesubtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='issues.issuesubtype'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='contact_medium',
            field=models.CharField(blank=True, choices=[('channel-alert', 'channel-alert'), ('facilitator', 'facilitator'), ('anonymous', 'anonymous')], default='channel-alert', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='contact_method',
            field=models.CharField(choices=[('email', 'email'), ('phone_number', 'phone_number'), ('whatsapp', 'whatsapp')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='intake_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When was the issue was reported'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='citizen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen_issues', to='issues.citizen'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='age_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='age_group_citizen', to='issues.citizenagegroup'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_citizen', to='issues.citizengroup'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='group_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group2_citizen', to='issues.citizengroup'),
        ),
    ]
