# Generated by Django 4.2 on 2025-08-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0009_issue_confirmed_issue_escalate_flag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubProjectGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="citizen",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("male", "Male"), ("female", "Female")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="alert_message_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                    ("closed", "closed"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="external_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="couchDB document _id",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="reject_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="issue",
            name="research_result",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="subcomponent",
            name="description",
            field=models.TextField(default="no description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subcomponent",
            name="parent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.component",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="citizen",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "keep_name_confidential",
                        "Keep name confidential. Only the person resolving the issue will see the name.",
                    ),
                    (
                        "on_behalf_of_someone",
                        "This is an individual filing on behalf of someone else.",
                    ),
                    (
                        "organization_behalf_someone",
                        "This is an organization filing on behalf of someone else.",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="contact_medium",
            field=models.CharField(
                blank=True,
                choices=[
                    ("anonymous", "Remain anonymous"),
                    ("facilitator", "Receive updates from facilitator"),
                    ("channel-alert", "Receive updates directly"),
                ],
                default="anonymous",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("email", "email"),
                    ("phone_number", "phone number"),
                    ("whatsapp", "whatsapp"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="subproject_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="issues.subprojectgroup",
            ),
        ),
    ]
