# Generated by Django 4.2 on 2025-08-27 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0010_subprojectgroup_citizen_gender_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="citizen",
            options={"verbose_name": "Citizen", "verbose_name_plural": "Citizens"},
        ),
        migrations.AlterModelOptions(
            name="citizenagegroup",
            options={
                "verbose_name": "Citizen Age Group",
                "verbose_name_plural": "Citizen Age Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="citizengroup",
            options={
                "verbose_name": "Citizen Group",
                "verbose_name_plural": "Citizen Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="component",
            options={"verbose_name": "Component", "verbose_name_plural": "Components"},
        ),
        migrations.AlterModelOptions(
            name="subcomponent",
            options={
                "verbose_name": "Subcomponent",
                "verbose_name_plural": "Subcomponents",
            },
        ),
        migrations.AlterModelOptions(
            name="subprojectgroup",
            options={
                "verbose_name": "Subproject Group",
                "verbose_name_plural": "Subproject Groups",
            },
        ),
        migrations.AddField(
            model_name="issuecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="issues.issuesubtype",
            ),
        ),
        migrations.AlterField(
            model_name="citizengroup",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("citizen_group", "Citizen group"),
                    ("citizen_group_2", "Citizen group 2"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created_date",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When was the issue created in DB",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("due_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="issues.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["-due_date"],
            },
        ),
    ]
