# Generated by Django 4.2 on 2025-08-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0011_alter_citizen_options_alter_citizenagegroup_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="issue_location",
        ),
        migrations.AlterField(
            model_name="issue",
            name="administrative_region",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific administrative location where the issue occurred.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="issues.administrativeregion",
            ),
        ),
    ]
