# Generated by Django 4.2 on 2025-09-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0012_remove_issue_issue_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="title",
        ),
    ]
