# Generated by Django 4.2 on 2025-09-04 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0013_remove_issue_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativelevel",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrativelevel",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="administrativeregion",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrativeregion",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="citizen",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="citizen",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="citizenagegroup",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="citizenagegroup",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="citizengroup",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="citizengroup",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="component",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="component",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="issuecategory",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issuecategory",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="issuedepartment",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issuedepartment",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="issuedepartmentadministrativelevel",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issuedepartmentadministrativelevel",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="issuestatus",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issuestatus",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="issuesubtype",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issuesubtype",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="issuetype",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issuetype",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="subcomponent",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subcomponent",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="subprojectgroup",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subprojectgroup",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at"),
        ),
    ]
