# Generated by Django 4.2 on 2025-09-10 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0014_administrativelevel_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="escalation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="reject_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="issue",
            name="reject_reason",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="research_result",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
