# Generated by Django 5.2.5 on 2025-09-08 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import issues.models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0014_administrativelevel_created_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="couchDB document _id",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="File attached to the issue",
                        upload_to=issues.models.issue_attachment_upload_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="issues.issue",
                        verbose_name="Issue",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["issue", "created_date"],
                        name="issues_issu_issue_i_cc40a5_idx",
                    ),
                    models.Index(fields=["uploaded_by"], name="issues_issu_uploade_72eadf_idx"),
                ],
            },
        ),
    ]
