# Generated by Django 4.2 on 2025-09-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0015_issue_escalation_reason_issue_rating_and_more"),
        ("issues", "0015_issueattachment"),
    ]

    operations = []
