# Generated by Django 4.2 on 2025-09-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0016_merge_20250910_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="appeal_status",
            field=models.BooleanField(default=False),
        ),
    ]
