# Generated by Django 4.2 on 2025-10-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0017_issue_appeal_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administrativelevel",
            options={
                "ordering": ["id"],
                "verbose_name": "Administrative Level",
                "verbose_name_plural": "Administrative Levels",
            },
        ),
        migrations.RenameField(
            model_name="issuecategory",
            old_name="redirection_protocol",
            new_name="redirection_protocol_to_delete",
        ),
        migrations.AddField(
            model_name="issuecategory",
            name="redirection_protocol_to_rename",
            field=models.SlugField(
                choices=[
                    ("department_head", "Department head"),
                    ("fewer_issues", "Person with fewer issues"),
                ],
                default="fewer_issues",
            ),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="gender",
            field=models.SlugField(
                blank=True,
                choices=[("", ""), ("male", "Male"), ("female", "Female")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="type",
            field=models.SlugField(
                blank=True,
                choices=[
                    (
                        "keep_name_confidential",
                        "Keep name confidential. Only the person resolving the issue will see the name.",
                    ),
                    (
                        "on_behalf_of_someone",
                        "This is an individual filing on behalf of someone else.",
                    ),
                    (
                        "organization_behalf_someone",
                        "This is an organization filing on behalf of someone else.",
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="citizengroup",
            name="type",
            field=models.SlugField(
                blank=True,
                choices=[
                    ("citizen_group", "Citizen group"),
                    ("citizen_group_2", "Citizen group 2"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="alert_message_status",
            field=models.SlugField(
                blank=True,
                choices=[
                    ("", ""),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                    ("closed", "closed"),
                ],
                default="",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="contact_medium",
            field=models.SlugField(
                blank=True,
                choices=[
                    ("anonymous", "Remain anonymous"),
                    ("facilitator", "Receive updates from facilitator"),
                    ("channel-alert", "Receive updates directly"),
                ],
                default="anonymous",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="contact_method",
            field=models.SlugField(
                blank=True,
                choices=[
                    ("", ""),
                    ("email", "email"),
                    ("phone_number", "phone number"),
                    ("whatsapp", "whatsapp"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issuecategory",
            name="confidentiality_level",
            field=models.SlugField(
                blank=True,
                choices=[("low", "Low"), ("anonymous", "Anonymous")],
                null=True,
            ),
        ),
    ]
