# Generated by Django 4.2 on 2025-10-03 10:47

from django.db import migrations, transaction

from grm.constants import DEPARTMENT_HEAD_CHOICE, FEWER_ISSUES_CHOICE


def update_redirection_protocol(apps, schema_editor):
    IssueCategory = apps.get_model('issues', 'IssueCategory')
    IssueCategory.objects.filter(redirection_protocol_to_delete=0).update(
        redirection_protocol_to_rename=DEPARTMENT_HEAD_CHOICE
    )
    IssueCategory.objects.filter(redirection_protocol_to_delete=1).update(
        redirection_protocol_to_rename=FEWER_ISSUES_CHOICE
    )


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0018_alter_administrativelevel_options_and_more"),
    ]

    operations = [
        migrations.RunPython(transaction.atomic(update_redirection_protocol)),
        migrations.RenameField(
            model_name="issuecategory",
            old_name="redirection_protocol_to_rename",
            new_name="redirection_protocol",
        ),
        migrations.RemoveField(
            model_name="issuecategory",
            name="redirection_protocol_to_delete",
        ),
    ]
