# Generated by Django 4.2 on 2025-10-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "issues",
            "0019_rename_redirection_protocol_to_rename_issuecategory_redirection_protocol_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuecategory",
            name="confidentiality_level",
            field=models.SlugField(choices=[("low", "Low"), ("anonymous", "Anonymous")], default="low"),
        ),
    ]
