# Generated by Django 4.2 on 2025-10-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0020_alter_issuecategory_confidentiality_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issuestatus",
            options={
                "ordering": ["id"],
                "verbose_name": "Issue Status",
                "verbose_name_plural": "Issue Status",
            },
        ),
        migrations.AlterField(
            model_name="issuestatus",
            name="open_status",
            field=models.BooleanField(default=False),
        ),
    ]
