# Generated by Django 4.2 on 2025-10-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0021_alter_issuestatus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizengroup",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="citizengroup",
            name="type",
            field=models.SlugField(
                blank=True,
                choices=[
                    ("citizen_group", "Citizen group"),
                    ("citizen_group_2", "Citizen group 2"),
                ],
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="issuecategory",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Abbreviation"),
        ),
        migrations.AlterField(
            model_name="issuecategory",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="issuecategory",
            name="redirection_protocol",
            field=models.SlugField(
                choices=[
                    ("department_head", "Department head"),
                    ("fewer_issues", "Person with fewer issues"),
                ],
                default="fewer_issues",
                verbose_name="Redirection protocol",
            ),
        ),
        migrations.AlterField(
            model_name="issuedepartment",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
