# Generated by Django 4.2 on 2025-10-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0022_alter_citizengroup_name_alter_citizengroup_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuecategory",
            name="confidentiality_level",
            field=models.SlugField(
                choices=[("low", "Low"), ("anonymous", "Anonymous")],
                default="low",
                verbose_name="Confidentiality level",
            ),
        ),
    ]
