# Generated by Django 4.2 on 2025-10-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0023_alter_issuecategory_confidentiality_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="vectorized",
            field=models.BooleanField(default=False),
        ),
    ]
