# Generated by Django 4.2 on 2025-10-31 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0024_issue_vectorized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuesubtype",
            name="parent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="issues.issuetype",
            ),
            preserve_default=False,
        ),
    ]
