# Generated by Django 4.2 on 2025-11-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0025_alter_issuesubtype_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuesubtype",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="issuesubtype",
            unique_together={("name", "parent")},
        ),
    ]
