# Generated by Django 4.2 on 2025-11-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0026_alter_issuesubtype_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subcomponent",
            unique_together={("name", "parent")},
        ),
    ]
