# Generated by Django 4.2 on 2025-11-13 13:35

from django.db import migrations, models


def populate_hierarchical_name(apps, schema_editor):
    """
    Populates hierarchical_name field for all existing AdministrativeRegions
    using a recursive CTE for efficiency.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Use a recursive CTE to build the hierarchy for all regions at once
        cursor.execute(
            """
            WITH RECURSIVE hierarchy_builder AS (
                -- Base case: start from all regions
                SELECT id,
                       name,
                       parent_id,
                       name::TEXT AS hierarchy_path
                FROM issues_administrativeregion

                UNION ALL

                -- Recursive case: append parent names
                SELECT hb.id,
                       hb.name,
                       ar.parent_id,
                       hb.hierarchy_path || ', ' || ar.name AS hierarchy_path
                FROM hierarchy_builder hb
                         INNER JOIN issues_administrativeregion ar ON hb.parent_id = ar.id)
            UPDATE issues_administrativeregion
            SET hierarchical_name = (SELECT hierarchy_path
                                     FROM hierarchy_builder
                                     WHERE hierarchy_builder.id = issues_administrativeregion.id
                                       AND hierarchy_builder.parent_id IS NULL)
            WHERE EXISTS (SELECT 1
                          FROM hierarchy_builder
                          WHERE hierarchy_builder.id = issues_administrativeregion.id
                            AND hierarchy_builder.parent_id IS NULL)
            """
        )


def reverse_hierarchical_name(apps, schema_editor):
    """
    Clears hierarchical_name field (for rollback).
    """
    AdministrativeRegion = apps.get_model('issues', 'AdministrativeRegion')
    AdministrativeRegion.objects.all().update(hierarchical_name='')


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0027_alter_subcomponent_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativeregion",
            name="hierarchical_name",
            field=models.TextField(db_index=True, default="", verbose_name="Hierarchical Name"),
        ),
        migrations.RunPython(populate_hierarchical_name, reverse_hierarchical_name),
    ]
