# Generated by Django 4.2 on 2025-11-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0028_administrativeregion_hierarchical_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuestatus",
            name="threshold_days",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Threshold in days for performance evaluation",
                verbose_name="Threshold days",
            ),
        ),
        migrations.AlterField(
            model_name="issuestatus",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AddConstraint(
            model_name="issuestatus",
            constraint=models.CheckConstraint(
                check=models.Q(("threshold_days__gt", 0)),
                name="issues_issuestatus_threshold_days_gt_0",
                violation_error_message="Threshold must be greater than zero.",
            ),
        ),
    ]
