# Generated by Django 4.2 on 2025-11-25 12:39

import django.utils.timezone
from django.core.management import call_command
from django.db import migrations, models


def populate_issue_status_changes(apps, schema_editor):
    """
    Run a bounded backfill of IssueStatusChange rows after the model table exists.

    IMPORTANT:
      - Keep this bounded to avoid long-running migrations.
      - For large datasets prefer running the backfill outside migrations (management command / Celery).
    """
    try:
        # === Safe bounded invocation ===
        # We call the management command with conservative limits so the migration remains bounded.
        # Adjust --limit and --batch-size to suit your environment.
        #
        # Examples of flags used:
        #   --limit 1000        -> process at most 1000 issues in this migration run
        #   --batch-size 500    -> process issues in batches of 500 (controls memory/transaction size)
        #   --dry-run           -> simulate only (uncomment to test without writing)
        #
        # Recommended: run a dry-run first on staging, then remove --dry-run for production.
        call_command(
            'backfill_status_changes',
            '--limit',
            '1000',
            '--batch-size',
            '500',
            # '--dry-run',  # uncomment to perform a dry-run (no DB writes)
        )
    except Exception:
        # Avoid failing the migration due to backfill errors.
        # If you prefer the migration to fail on backfill errors, re-raise the exception instead.
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0029_issuestatus_threshold_days_alter_issuestatus_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entered_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "exited_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="issues.issue",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_changes",
                        to="issues.issuestatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Status Change",
                "verbose_name_plural": "Issue Status Changes",
                "ordering": ["-entered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="issuestatuschange",
            index=models.Index(
                fields=["issue", "status", "entered_at"],
                name="issues_issu_issue_i_f848e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuestatuschange",
            index=models.Index(fields=["status", "entered_at"], name="issues_issu_status__a64922_idx"),
        ),
        migrations.RunPython(populate_issue_status_changes, reverse_code=migrations.RunPython.noop),
    ]
