# Generated by Django 4.2 on 2025-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0031_add_indexes_issuestatuschange"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueattachment",
            name="deleted_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
    ]
