# Generated by Django 4.2 on 2026-01-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0032_issueattachment_deleted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuestatus",
            name="threshold_days_to_escalate",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Threshold in days to escalate an issue",
                null=True,
                verbose_name="Threshold days to escalate",
            ),
        ),
    ]
