# Generated by Django 4.2 on 2026-05-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0033_issuestatus_threshold_days_to_escalate"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="appeal_reason",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
