# Generated by Django 4.2 on 2025-11-19 17:51

import django.utils.timezone
from django.core.management import call_command
from django.db import migrations, models


def populate_metrics(apps, schema_editor):
    """
    Populate initial metrics after the table exists.
    WARNING: keep this bounded (limit regions/categories) to avoid very long migrations.
    For a full backfill use the management command outside of migration.
    """
    # Example: only create global metrics + a small sample of regions/categories
    try:
        call_command(
            "populate_performance_metrics",
            "--create-global",
            "--create-regions",
            "--limit-regions",
            "10",
            "--create-categories",
            "--limit-categories",
            "10",
            "--no-progress",
        )
    except Exception:
        # Avoid failing the migration due to command failure; log or ignore depending on policy
        # Re-raise if you prefer migration to fail hard
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0028_administrativeregion_hierarchical_name"),
        ("dashboard", "0002_alter_project_description_alter_project_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("7d", "Last 7 Days"),
                            ("30d", "Last 30 Days"),
                            ("90d", "Last 90 Days"),
                        ],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                (
                    "active_users_count",
                    models.IntegerField(default=0, help_text="Number of active users in chosen window"),
                ),
                (
                    "active_users_metric",
                    models.CharField(
                        default="WAU",
                        help_text="Metric name: DAU/WAU/MAU/QAU",
                        max_length=10,
                    ),
                ),
                (
                    "active_users_change_percentage",
                    models.FloatField(default=0.0, help_text="Percentage change from previous period"),
                ),
                (
                    "new_issues_count",
                    models.IntegerField(default=0, help_text="Total new issues created in period"),
                ),
                (
                    "new_issues_change_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage change of new issues count from previous period",
                    ),
                ),
                (
                    "average_resolution_days",
                    models.FloatField(default=0.0, help_text="Average days to resolve issues"),
                ),
                (
                    "resolution_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of issues resolved vs total issues",
                    ),
                ),
                ("total_resolved_issues", models.IntegerField(default=0)),
                ("total_issues", models.IntegerField(default=0)),
                (
                    "resolution_change_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage change in resolution time from previous period",
                    ),
                ),
                (
                    "resolution_rate_change_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage change of resolution rate from previous period",
                    ),
                ),
                (
                    "average_satisfaction_score",
                    models.FloatField(default=0.0, help_text="Average rating score (1-5)"),
                ),
                (
                    "appeal_rate",
                    models.FloatField(default=0.0, help_text="Percentage of issues appealed"),
                ),
                ("total_appeals", models.IntegerField(default=0)),
                ("total_rated_issues", models.IntegerField(default=0)),
                (
                    "satisfaction_change_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage change in satisfaction from previous period",
                    ),
                ),
                (
                    "appeal_rate_change_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage change of appeal rate from previous period",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "administrative_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="issues.administrativeregion",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="issues.issuecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Metrics",
                "verbose_name_plural": "Performance Metrics",
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="performancemetrics",
            index=models.Index(
                fields=[
                    "period",
                    "administrative_region",
                    "category",
                    "-calculated_at",
                ],
                name="dashboard_p_period_6d91aa_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performancemetrics",
            unique_together={
                (
                    "period",
                    "start_date",
                    "end_date",
                    "administrative_region",
                    "category",
                )
            },
        ),
        migrations.RunPython(populate_metrics, reverse_code=migrations.RunPython.noop),
    ]
