# Generated by Django 4.2 on 2025-11-25 12:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_performancemetrics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusBottleneckMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("7d", "Last 7 Days"),
                            ("30d", "Last 30 Days"),
                            ("90d", "Last 90 Days"),
                        ],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                ("issues_count", models.IntegerField(default=0)),
                ("average_time_in_status_days", models.FloatField(default=0.0)),
                (
                    "calculated_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "administrative_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issues.administrativeregion",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issues.issuecategory",
                    ),
                ),
                (
                    "issue_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issues.issuestatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Bottleneck Metric",
                "verbose_name_plural": "Status Bottleneck Metrics",
            },
        ),
        migrations.AddIndex(
            model_name="statusbottleneckmetrics",
            index=models.Index(
                fields=[
                    "period",
                    "administrative_region",
                    "category",
                    "issue_status",
                    "-calculated_at",
                ],
                name="dashboard_s_period_92c1f2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="statusbottleneckmetrics",
            unique_together={
                (
                    "period",
                    "start_date",
                    "end_date",
                    "administrative_region",
                    "category",
                    "issue_status",
                )
            },
        ),
    ]
