# Generated by Django 4.2 on 2025-12-01 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0031_add_indexes_issuestatuschange"),
        ("dashboard", "0004_statusbottleneckmetrics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionPerformanceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("7d", "7d"), ("30d", "30d"), ("90d", "90d")],
                        max_length=3,
                    ),
                ),
                ("open_issues_count", models.IntegerField(default=0)),
                ("avg_resolution_days", models.FloatField(default=0.0)),
                ("active_workers_count", models.IntegerField(default=0)),
                ("total_workers_in_region", models.IntegerField(default=0)),
                ("open_issues_score", models.FloatField(default=100.0)),
                ("resolution_score", models.FloatField(default=100.0)),
                ("active_workers_score", models.FloatField(default=100.0)),
                ("overall_performance_score", models.FloatField(default=100.0)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issues.issuecategory",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_performance_metrics",
                        to="issues.administrativeregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region Performance Metrics",
                "verbose_name_plural": "Region Performance Metrics",
            },
        ),
        migrations.AddIndex(
            model_name="regionperformancemetrics",
            index=models.Index(
                fields=["period", "category", "-overall_performance_score"],
                name="dashboard_r_period_cfd6af_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="regionperformancemetrics",
            unique_together={("region", "category", "period")},
        ),
    ]
