# Generated by Django 3.2 on 2023-04-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_cdata_pdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdata',
            options={'verbose_name_plural': 'Cdata'},
        ),
        migrations.AlterModelOptions(
            name='pdata',
            options={'verbose_name_plural': 'Pdata'},
        ),
    ]
