# Generated by Django 5.2.5 on 2025-08-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20230105_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='couch DB ID'),
        ),
    ]
