# Generated by Django 4.2 on 2025-08-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_user_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="external_id",
            field=models.CharField(
                default=None,
                max_length=255,
                null=True,
                verbose_name="couchDB document _id",
            ),
        ),
    ]
