# Generated by Django 4.2 on 2025-08-25 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0010_subprojectgroup_citizen_gender_and_more"),
        ("authentication", "0008_alter_user_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facilitator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_region", models.BooleanField(null=True)),
                ("village_secretary", models.BooleanField(null=True)),
                (
                    "administrative_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilitators",
                        to="issues.administrativeregion",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="issues.issuedepartment",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facilitator",
                "verbose_name_plural": "Facilitators",
            },
        ),
    ]
