# Generated by Django 4.2 on 2025-08-25 10:28

from django.db import migrations, transaction


def update_administrative_region(apps, schema_editor):
    GovernmentWorker = apps.get_model('authentication', 'GovernmentWorker')
    objects_to_update = []

    for obj in GovernmentWorker.objects.all():
        if obj.administrative_id:
            if obj.administrative_id.isdigit():
                obj.administrative_id = str(int(obj.administrative_id) + 1)
            elif obj.administrative_id == 'country':
                obj.administrative_id = '1'
            objects_to_update.append(obj)

    GovernmentWorker.objects.bulk_update(objects_to_update, ['administrative_id'])


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_facilitator"),
    ]

    operations = [
        migrations.RunPython(transaction.atomic(update_administrative_region)),
    ]
