# Generated by Django 4.2 on 2025-08-27 18:52

import django.db.models.deletion
from django.db import migrations, models, transaction


def set_new_fields(apps, schema_editor):
    from django.db.models import F, Func, IntegerField

    GovernmentWorker = apps.get_model('authentication', 'GovernmentWorker')
    GovernmentWorker.objects.update(
        issue_department=F("department"),
        administrative_region=Func(
            F("administrative_id"),
            function="CAST",
            template="CAST(%(expressions)s AS INTEGER)",
            output_field=IntegerField(),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0011_alter_citizen_options_alter_citizenagegroup_options_and_more"),
        ("authentication", "0010_update_administrative_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="governmentworker",
            name="administrative_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.administrativeregion",
                verbose_name="administrative region",
            ),
        ),
        migrations.AddField(
            model_name="governmentworker",
            name="issue_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.issuedepartment",
                verbose_name="department",
            ),
        ),
        migrations.RunPython(transaction.atomic(set_new_fields)),
    ]
