# Generated by Django 4.2 on 2025-08-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_governmentworker_administrative_region_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="governmentworker",
            name="administrative_id",
        ),
        migrations.RemoveField(
            model_name="governmentworker",
            name="department",
        ),
    ]
