# Generated by Django 4.2 on 2025-08-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_remove_governmentworker_administrative_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="governmentworker",
            old_name="issue_department",
            new_name="department",
        ),
    ]
