# Generated by Django 4.2 on 2025-08-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0011_alter_citizen_options_alter_citizenagegroup_options_and_more"),
        ("authentication", "0013_rename_issue_department_governmentworker_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="governmentworker",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.issuedepartment",
                verbose_name="department",
            ),
            preserve_default=False,
        ),
    ]
