# Generated by Django 4.2 on 2025-09-04 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_alter_governmentworker_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facilitator",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
