# Generated by Django 4.2 on 2025-09-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_facilitator_created_date_facilitator_updated_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grm_manager",
            field=models.BooleanField(default=False),
        ),
    ]
