# Generated by Django 4.2 on 2025-10-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0023_alter_issuecategory_confidentiality_level"),
        ("authentication", "0017_citizen"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="citizen",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_citizen",
                to="issues.citizen",
            ),
        ),
    ]
