# Generated by Django 4.2 on 2025-10-22 14:14

from django.db import migrations, transaction


def set_default_citizen(apps, schema_editor):
    Citizen = apps.get_model('authentication', 'Citizen')
    IssuesCitizen = apps.get_model('issues', 'Citizen')
    for user_citizen in Citizen.objects.select_related('user', 'citizen'):
        if not user_citizen.citizen:
            name = f"{user_citizen.user.first_name} {user_citizen.user.last_name}"
            citizen = IssuesCitizen.objects.create(name=name)
            user_citizen.citizen = citizen
            user_citizen.save()


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0018_citizen_citizen"),
    ]

    operations = [migrations.RunPython(transaction.atomic(set_default_citizen))]
