# Generated by Django 4.2 on 2025-10-22 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0023_alter_issuecategory_confidentiality_level"),
        ("authentication", "0019_set_default_citizen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="citizen",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_citizen",
                to="issues.citizen",
            ),
            preserve_default=False,
        ),
    ]
