# Generated by Django 4.2 on 2025-10-22 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0023_alter_issuecategory_confidentiality_level"),
        ("authentication", "0020_alter_citizen_citizen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="citizen",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_citizen",
                to="issues.citizen",
            ),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
