# Generated by Django 4.2 on 2025-11-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0021_alter_citizen_citizen_alter_citizen_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grm_owner",
            field=models.BooleanField(default=False),
        ),
    ]
