# Generated by Django 4.2 on 2025-11-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0027_alter_subcomponent_unique_together"),
        ("authentication", "0022_user_grm_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilitator",
            name="department",
        ),
        migrations.AlterField(
            model_name="facilitator",
            name="administrative_region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilitators",
                to="issues.administrativeregion",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="governmentworker",
            name="administrative_region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.administrativeregion",
                verbose_name="administrative region",
            ),
            preserve_default=False,
        ),
    ]
