# Generated by Django 4.2 on 2025-12-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0023_remove_facilitator_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the user performed any activity (login, comment, issue creation/modification)",
                null=True,
                verbose_name="last activity",
            ),
        ),
    ]
