from django.urls import path

from issues.views import (
    AssigneeIssueListAPIView,
    CitizenAgeGroupListAPIView,
    CitizenGroupListAPIView,
    ComponentListAPIView,
    IssueAttachmentCreateAPIView,
    IssueAttachmentsListAPIView,
    IssueCategoryListAPIView,
    IssueCommentCreateAPIView,
    IssueCommentDeleteAPIView,
    IssueCommentsListAPIView,
    IssueCreateAPIView,
    IssueRetrieveAPIView,
    IssueStatusListAPIView,
    IssueSubTypeListAPIView,
    IssueTypeListAPIView,
    IssueUpdateAPIView,
    ReporterIssueListAPIView,
    SubComponentListAPIView,
    SubProjectGroupListAPIView,
)

app_name = "issues"
urlpatterns = [
    path('create/', IssueCreateAPIView.as_view(), name='create-issue'),
    path('<int:id>/update/', IssueUpdateAPIView.as_view(), name='update-issue'),
    path("assignee/", AssigneeIssueListAPIView.as_view(), name="list-assigned-issues"),
    path("reporter/", ReporterIssueListAPIView.as_view(), name="list-reported-issues"),
    path('<int:id>/', IssueRetrieveAPIView.as_view(), name='issue-detail'),
    path('issue-statuses/', IssueStatusListAPIView.as_view(), name='list-issue-statuses'),
    path('components/', ComponentListAPIView.as_view(), name='list-components'),
    path('subcomponents/', SubComponentListAPIView.as_view(), name='list-subcomponents'),
    path('subproject-groups/', SubProjectGroupListAPIView.as_view(), name='list-subproject-groups'),
    path('citizen-age-groups/', CitizenAgeGroupListAPIView.as_view(), name='list-citizen-age-groups'),
    path('citizen-groups/', CitizenGroupListAPIView.as_view(), name='list-citizen-groups'),
    path('issue-types/', IssueTypeListAPIView.as_view(), name='list-issue-types'),
    path('issue-subtypes/', IssueSubTypeListAPIView.as_view(), name='list-issue-subtypes'),
    path('issue-categories/', IssueCategoryListAPIView.as_view(), name='list-issue-categories'),
    path('<int:id>/add-comment', IssueCommentCreateAPIView.as_view(), name='add-issue-comment'),
    path('<int:id>/comments/', IssueCommentsListAPIView.as_view(), name='list-issue-comments'),
    path('<int:id>/add-attachment', IssueAttachmentCreateAPIView.as_view(), name='add-issue-attachment'),
    path('<int:id>/attachments/', IssueAttachmentsListAPIView.as_view(), name='list-issue-attachments'),
    path('delete-comment/<int:id>/', IssueCommentDeleteAPIView.as_view(), name='delete-issue-comment'),
]
