repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
    - id: pyupgrade
      args: [ --py311-plus ]  # o tu versión de Python

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4  # última versión
  hooks:
    - id: ruff
      args: [ --fix ]

- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.25.0
  hooks:
    - id: commitizen
      stages: [ commit-msg ]
      verbose: true

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black"]
      stages: [ commit ]
      name: isort (python)
      verbose: true

- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
    language_version: python3
    stages: [ commit ]
    args:
      - "--line-length=120"
      - "--skip-string-normalization"
    verbose: true

