# Generated by Django 4.2 on 2025-09-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WizardSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome"),
                            ("admin_levels", "Admin Levels"),
                            ("roles", "Roles"),
                            ("entry_types", "Entry Types"),
                            ("categories", "Categories"),
                            ("feedback", "Feedback"),
                            ("complete", "Complete"),
                        ],
                        default="welcome",
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wizard Session",
                "verbose_name_plural": "Wizard Sessions",
            },
        ),
    ]
