# Generated by Django 4.2 on 2025-09-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wizard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WizardSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("prompt", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=50,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wizard Section",
                "verbose_name_plural": "Wizard Section",
            },
        ),
        migrations.DeleteModel(
            name="WizardSession",
        ),
    ]
