# Generated by Django 4.2 on 2025-09-22 11:11

from django.db import migrations, transaction


def create_wizard_sections(apps, schema_editor):
    WizardSection = apps.get_model('wizard', 'WizardSection')
    objects_to_create = []
    wizard_sections = (
        'Project Description',
        'Administrative Levels',
        'GRM Roles & Responsibilities',
        'Grievance Types',
        'Categories & Teams',
        'Routing Rules',
        'Feedback & Appeal',
    )

    for name in wizard_sections:
        objects_to_create.append(WizardSection(name=name, template_name=f'{name.lower().replace(' ', '_')}.html'))

    WizardSection.objects.bulk_create(objects_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("wizard", "0002_wizardsection_delete_wizardsession"),
    ]

    operations = [
        migrations.RunPython(transaction.atomic(create_wizard_sections)),
    ]
