# Generated by Django 4.2 on 2025-09-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wizard", "0002_wizardsection_delete_wizardsession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wizardsection",
            options={
                "ordering": ["id"],
                "verbose_name": "Wizard Section",
                "verbose_name_plural": "Wizard Section",
            },
        ),
        migrations.RemoveField(
            model_name="wizardsection",
            name="template_name",
        ),
    ]
