# Generated by Django 4.2 on 2025-10-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wizard", "0004_alter_wizardsection_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wizardsection",
            name="status",
            field=models.SlugField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="not_started",
            ),
        ),
    ]
