# Generated by Django 4.2 on 2025-10-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wizard", "0006_alter_wizardsection_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wizardsection",
            name="name",
            field=models.SlugField(
                choices=[
                    ("project", "Project Description"),
                    (
                        "administrative_levels",
                        "Administrative Level Structure Configuration",
                    ),
                    ("administrative_regions", "Load Administrative Levels"),
                    ("departments", "Departments"),
                    ("categories", "Issues Categories"),
                    ("issue_status", "Resolution Process"),
                    ("citizen_age_groups", "Citizen Age Groups"),
                    ("citizen_groups", "Citizen Groups"),
                    ("components", "Project Components"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
