# Generated by Django 4.2 on 2025-10-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wizard", "0007_alter_wizardsection_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wizardsection",
            options={
                "ordering": ["step"],
                "verbose_name": "Wizard Section",
                "verbose_name_plural": "Wizard Sections",
            },
        ),
        migrations.AddField(
            model_name="wizardsection",
            name="step",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
