# Generated by Django 4.2 on 2025-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wizard", "0009_wizardsection_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wizardsection",
            name="name",
            field=models.SlugField(
                choices=[
                    ("project", "Project Description"),
                    (
                        "administrative_levels",
                        "Administrative Level Structure Configuration",
                    ),
                    ("administrative_regions", "Load Administrative Levels"),
                    ("departments", "Departments"),
                    ("issue_types", "Types"),
                    ("categories", "Issues Categories"),
                    ("issue_status", "Resolution Process"),
                    ("citizen_age_groups", "Citizen Age Groups"),
                    ("citizen_groups", "Citizen Groups"),
                    ("components", "Project Components"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="wizardsection",
            name="step",
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
